# deploy — make reality match the manifest.
#
# Idempotent, so running it after a git pull on a second machine is the whole
# setup process. Policy lives here; the symlinking itself is rig::link.

rig::load log link proc
rack::load manifest

RACK_MODULE_SUMMARY[deploy]="link everything in the manifest into place"
RACK_MODULE_ACTIONS[deploy]="run status remove adopt"
RACK_MODULE_STATUS[deploy]="ready"
RACK_MODULE_TIER[deploy]="core"

# Where --force puts what it replaces, keeping its path under $HOME:
# ~/.config/hypr lands at <backups>/<stamp>/.config/hypr. Moved, never
# deleted — the thing in the way on a fresh machine is usually a config the
# app wrote on first launch, but it can as easily be one you meant to keep.
rack::deploy::__backup() {
    local target=$1 stamp=$2 rel dest
    rel=${target#"$HOME"/}
    [[ $rel == "$target" ]] && rel=${target#/}
    dest="$HOME/.local/state/rack/backups/$stamp/$rel"
    mkdir -p -- "${dest%/*}" && mv -- "$target" "$dest" || return 1
    printf '%s\n' "$dest"
}

# Is this a config nobody has touched — what an app wrote for itself on
# first launch, before the repo's was linked? Then it goes aside without
# asking for --force. Only two shapes count, both checked against the real
# programs: ghostty's first launch writes an empty config.ghostty, and
# Hyprland's writes an example marked `autogenerated` (0.56:
# `hl.config({ autogenerated = true })`, or `autogenerated = 1` in the old
# format). Every file has to be one of those; anything else is somebody's
# config and still needs --force. A directory with no files in it at all
# passes too: it holds nothing to lose, and it is what an app's
# interrupted first launch can leave behind.
rack::deploy::__untouched() {
    local target=$1 file
    [[ -e $target && ! -L $target ]] || return 1
    while IFS= read -r -d '' file; do
        [[ -s $file ]] || continue
        grep -Eq '^[[:space:]]*(hl\.config\(\{[[:space:]]*autogenerated[[:space:]]*=[[:space:]]*true|autogenerated[[:space:]]*=[[:space:]]*1)' -- "$file" ||
            return 1
    done < <(find "$target" -type f -print0 2>/dev/null)
    return 0
}

# What an entry was before it was linked, in words, for the row's aside.
rack::deploy::__was() {
    case $1 in
        absent) printf 'new' ;;
        stale) printf 'was linked elsewhere' ;;
        broken) printf 'was a dangling link' ;;
        conflict) printf 'replaced what was there' ;;
    esac
}

# An entry that could not be deployed: on a terminal a ✗ row with the
# reason, plain the error line it always was.
rack::deploy::__fail() {
    if rack::ui::rich; then
        rack::ui::row bad "$1" "$2" >&2
    else
        rig::log::error "$1: $2"
    fi
}

# run [--force] [--adopt] [name...]
rack::deploy::run() {
    local force=0 adopt=0
    local -a names=()
    while (($#)); do
        case $1 in
            --force) force=1 ;;
            --adopt) adopt=1 ;;
            --) ;;
            -*)
                rig::log::error "deploy: unknown option: $1"
                return "$RIG_EX_USAGE"
                ;;
            *) names+=("$1") ;;
        esac
        shift
    done

    local name source target reload state moved why changed=0 failed=0 inplace=0 planned=0
    local stamp entries
    stamp=$(date +%Y%m%d-%H%M%S)

    # Selected up front rather than read through a process substitution,
    # which would drop select's status: a name that isn't in the manifest
    # (`rack deploy hyrp`) would log its error and then report "nothing to
    # do" with success.
    entries=$(rack::manifest::select "${names[@]}") || return $?
    [[ -n $entries ]] && rack::manifest::header "Deploy" "$entries"

    while IFS=$'\t' read -r name source target reload; do
        [[ -n $name ]] || continue
        state=$(rig::link::check "$source" "$target") || true

        case $state in
            ok)
                # On a terminal an entry already in place is counted, not
                # listed: among thirty of them the two that changed are
                # what you are looking for.
                inplace=$((inplace + 1))
                rack::ui::rich || printf '  %-12s ok\n' "$name"
                continue
                ;;

            conflict)
                # Something real is in the way. Adopting moves it into the
                # repo and links back, which is the sane first-run move on a
                # machine that had configuration before it had a repo.
                if ((adopt)); then
                    if [[ -e $source ]]; then
                        rack::deploy::__fail "$name" "cannot adopt, $source already exists in the repo"
                        failed=$((failed + 1))
                        continue
                    fi
                    if [[ ${RIG_DRY_RUN:-0} != 0 ]]; then
                        rack::ui::item skip "$name" "would adopt ${target/#$HOME/\~}" \
                            "would adopt" "${target/#$HOME/\~}"
                        planned=$((planned + 1))
                        continue
                    fi
                    rig::link::adopt "$target" "$source" || {
                        failed=$((failed + 1))
                        continue
                    }
                    rack::ui::item ok "$name" "adopted" "adopted into the repo" "${target/#$HOME/\~}"
                    changed=$((changed + 1))
                    continue
                fi
                why=""
                rack::deploy::__untouched "$target" && why=" (untouched default)"
                if ((!force)) && [[ -z $why ]]; then
                    # --adopt can only take it when the repo has no copy
                    # of its own, which for a manifest entry is almost
                    # never — so name the one that will actually work.
                    if [[ -e $source ]]; then
                        rack::deploy::__fail "$name" "${target/#$HOME/\~} exists and is not ours (--force moves it aside)"
                    else
                        rack::deploy::__fail "$name" "${target/#$HOME/\~} exists and is not ours (--adopt moves it into the repo)"
                    fi
                    failed=$((failed + 1))
                    continue
                fi
                if [[ ${RIG_DRY_RUN:-0} != 0 ]]; then
                    rack::ui::item skip "$name" "would move aside$why and link"
                    planned=$((planned + 1))
                    continue
                fi
                moved=$(rack::deploy::__backup "$target" "$stamp") || {
                    rack::deploy::__fail "$name" "could not move ${target/#$HOME/\~} aside"
                    failed=$((failed + 1))
                    continue
                }
                rack::ui::item warn "$name" "moved aside$why to ${moved/#$HOME/\~}" \
                    "moved aside$why" "${moved/#$HOME/\~}"
                ;;
        esac

        if [[ ${RIG_DRY_RUN:-0} != 0 ]]; then
            rack::ui::item skip "$name" "would link ($state)" "would link" "$(rack::deploy::__was "$state")"
            planned=$((planned + 1))
            continue
        fi

        if rig::link::make "$source" "$target"; then
            rack::ui::item ok "$name" "linked ($state)" "linked" "$(rack::deploy::__was "$state")"
            changed=$((changed + 1))
        else
            rack::ui::rich && rack::ui::row bad "$name" "could not link" >&2
            failed=$((failed + 1))
        fi
    done <<<"$entries"

    if ! rack::ui::rich; then
        ((failed)) && {
            rig::log::error "$failed entr(ies) could not be deployed"
            return "$RIG_EX_FAIL"
        }
        ((changed)) || rig::log::info "nothing to do"
        return 0
    fi

    # Nothing listed above means everything was in place: say so as a row,
    # rather than leave a gap under the header.
    local rest=""
    if ((changed + failed + planned == 0)); then
        ((inplace)) && rack::ui::row ok "all $inplace" "already in place"
    elif ((inplace)); then
        rest="$inplace already in place"
    fi
    if ((failed)); then
        rack::ui::finish bad "$(rack::ui::plural "$failed" entry entries) could not be deployed" "$rest"
        return "$RIG_EX_FAIL"
    elif [[ ${RIG_DRY_RUN:-0} != 0 ]]; then
        rack::ui::finish info "Dry run — nothing changed" "$rest"
    elif ((changed)); then
        rack::ui::finish ok "Linked $changed" "$rest"
    else
        rack::ui::finish ok "Nothing to do"
    fi
    return 0
}

# What deploy would say, without doing anything.
rack::deploy::status() {
    local name source target reload state entries linked=0 total=0
    local -A level=([ok]=ok [absent]=skip [stale]=warn [broken]=bad [conflict]=warn)
    local -A words=([ok]=linked [absent]="not deployed" [stale]="links elsewhere"
        [broken]="dangling link" [conflict]="real file in the way")
    entries=$(rack::manifest::select "$@") || return $?
    [[ -n $entries ]] && rack::manifest::header "Deploy status" "$entries"
    while IFS=$'\t' read -r name source target reload; do
        [[ -n $name ]] || continue
        state=$(rig::link::check "$source" "$target") || true
        total=$((total + 1))
        [[ $state == ok ]] && linked=$((linked + 1))
        if rack::ui::rich; then
            rack::ui::row "${level[$state]:-warn}" "$name" "${words[$state]:-$state}" "${target/#$HOME/\~}"
        else
            printf '  %-12s %-9s %s\n' "$name" "$state" "${target/#$HOME/\~}"
        fi
    done <<<"$entries"

    rack::ui::rich && ((total)) || return 0
    if ((linked == total)); then
        rack::ui::finish ok "All $total linked"
    else
        rack::ui::finish warn "$linked of $total linked" "rack deploy links the rest"
    fi
}

# The one you need the moment you drop an app from the manifest.
rack::deploy::remove() {
    local name source target reload dotfiles entries removed=0
    dotfiles=$(rack::manifest::dotfiles)
    entries=$(rack::manifest::select "$@") || return $?
    [[ -n $entries ]] && rack::manifest::header "Deploy remove" "$entries"

    while IFS=$'\t' read -r name source target reload; do
        [[ -n $name ]] || continue
        if ! rig::link::points_into "$target" "$dotfiles"; then
            [[ -e $target ]] && rack::ui::item skip "$name" "left alone (not ours)"
            continue
        fi
        if [[ ${RIG_DRY_RUN:-0} != 0 ]]; then
            rack::ui::item skip "$name" "would unlink"
            continue
        fi
        rig::link::remove "$target" --into "$dotfiles" &&
            rack::ui::item ok "$name" "unlinked" "unlinked" "${target/#$HOME/\~}"
        removed=$((removed + 1))
    done <<<"$entries"

    if ((removed)); then
        rack::ui::rich && rack::ui::finish ok "Unlinked $removed"
    else
        rack::ui::finish info "nothing to remove"
    fi
    return 0
}

# adopt <name...> — explicit form of the same move deploy --adopt makes.
rack::deploy::adopt() {
    (($#)) || {
        rig::log::error "adopt: name which entries to adopt"
        return "$RIG_EX_USAGE"
    }
    rack::deploy::run --adopt "$@"
}

rack::deploy::__default() { rack::deploy::run "$@"; }

rack::deploy::__usage() {
    cat <<'EOF'
  rack deploy                    everything in the manifest
  rack deploy hypr nvim          just these
  rack deploy --adopt            move what is already there into the repo first
  rack deploy --force            replace real files, moving them to
                                 ~/.local/state/rack/backups/<time>/
                                 (an app's untouched first-launch config
                                 is moved there without --force)
  rack deploy status             what it would do
  rack deploy remove nvim        unlink, but only links pointing into the repo

Idempotent: already-correct entries are left alone, so running this after a
git pull is the whole setup step. Honours RIG_DRY_RUN=1.
EOF
}
