# deploy — make reality match the manifest.
#
# Idempotent, so running it after a git pull on a second machine is the whole
# setup process. Policy lives here; the symlinking itself is rig::link.

rig::load log link proc
rack::load manifest

RACK_MODULE_SUMMARY[deploy]="link everything in the manifest into place"
RACK_MODULE_ACTIONS[deploy]="run status remove adopt"
RACK_MODULE_STATUS[deploy]="ready"
RACK_MODULE_TIER[deploy]="core"

# Where --force puts what it replaces, keeping its path under $HOME:
# ~/.config/hypr lands at <backups>/<stamp>/.config/hypr. Moved, never
# deleted — the thing in the way on a fresh machine is usually a config the
# app wrote on first launch, but it can as easily be one you meant to keep.
rack::deploy::__backup() {
    local target=$1 stamp=$2 rel dest
    rel=${target#"$HOME"/}
    [[ $rel == "$target" ]] && rel=${target#/}
    dest="$HOME/.local/state/rack/backups/$stamp/$rel"
    mkdir -p -- "${dest%/*}" && mv -- "$target" "$dest" || return 1
    printf '%s\n' "$dest"
}

# Is this a config nobody has touched — what an app wrote for itself on
# first launch, before the repo's was linked? Then it goes aside without
# asking for --force. Only two shapes count, both checked against the real
# programs: ghostty's first launch writes an empty config.ghostty, and
# Hyprland's writes an example marked `autogenerated` (0.56:
# `hl.config({ autogenerated = true })`, or `autogenerated = 1` in the old
# format). Every file has to be one of those; anything else is somebody's
# config and still needs --force.
rack::deploy::__untouched() {
    local target=$1 file
    [[ -e $target && ! -L $target ]] || return 1
    while IFS= read -r -d '' file; do
        [[ -s $file ]] || continue
        grep -Eq '^[[:space:]]*(hl\.config\(\{[[:space:]]*autogenerated[[:space:]]*=[[:space:]]*true|autogenerated[[:space:]]*=[[:space:]]*1)' -- "$file" ||
            return 1
    done < <(find "$target" -type f -print0 2>/dev/null)
    return 0
}

# run [--force] [--adopt] [name...]
rack::deploy::run() {
    local force=0 adopt=0
    local -a names=()

    while (($#)); do
        case $1 in
            --force) force=1 ;;
            --adopt) adopt=1 ;;
            --) ;;
            -*)
                rig::log::error "deploy: unknown option: $1"
                return "$RIG_EX_USAGE"
                ;;
            *) names+=("$1") ;;
        esac
        shift
    done

    local name source target reload state moved why changed=0 failed=0
    local stamp
    stamp=$(date +%Y%m%d-%H%M%S)

    while IFS=$'\t' read -r name source target reload; do
        state=$(rig::link::check "$source" "$target") || true

        case $state in
            ok)
                printf '  %-12s ok\n' "$name"
                continue
                ;;

            conflict)
                # Something real is in the way. Adopting moves it into the
                # repo and links back, which is the sane first-run move on a
                # machine that had configuration before it had a repo.
                if ((adopt)); then
                    if [[ -e $source ]]; then
                        rig::log::error "$name: cannot adopt, $source already exists in the repo"
                        failed=$((failed + 1))
                        continue
                    fi
                    if [[ ${RIG_DRY_RUN:-0} != 0 ]]; then
                        printf '  %-12s would adopt %s\n' "$name" "${target/#$HOME/\~}"
                        continue
                    fi
                    rig::link::adopt "$target" "$source" || {
                        failed=$((failed + 1))
                        continue
                    }
                    printf '  %-12s adopted\n' "$name"
                    changed=$((changed + 1))
                    continue
                fi
                why=""
                rack::deploy::__untouched "$target" && why=" (untouched default)"
                if ((!force)) && [[ -z $why ]]; then
                    # --adopt can only take it when the repo has no copy
                    # of its own, which for a manifest entry is almost
                    # never — so name the one that will actually work.
                    if [[ -e $source ]]; then
                        rig::log::error "$name: ${target/#$HOME/\~} exists and is not ours (--force moves it aside)"
                    else
                        rig::log::error "$name: ${target/#$HOME/\~} exists and is not ours (--adopt moves it into the repo)"
                    fi
                    failed=$((failed + 1))
                    continue
                fi
                if [[ ${RIG_DRY_RUN:-0} != 0 ]]; then
                    printf '  %-12s would move aside%s and link\n' "$name" "$why"
                    continue
                fi
                moved=$(rack::deploy::__backup "$target" "$stamp") || {
                    rig::log::error "$name: could not move ${target/#$HOME/\~} aside"
                    failed=$((failed + 1))
                    continue
                }
                printf '  %-12s moved aside%s to %s\n' "$name" "$why" "${moved/#$HOME/\~}"
                ;;
        esac

        if [[ ${RIG_DRY_RUN:-0} != 0 ]]; then
            printf '  %-12s would link (%s)\n' "$name" "$state"
            continue
        fi

        if rig::link::make "$source" "$target"; then
            printf '  %-12s linked (%s)\n' "$name" "$state"
            changed=$((changed + 1))
        else
            failed=$((failed + 1))
        fi
    done < <(rack::manifest::select "${names[@]}")

    ((failed)) && {
        rig::log::error "$failed entr(ies) could not be deployed"
        return "$RIG_EX_FAIL"
    }
    ((changed)) || rig::log::info "nothing to do"
    return 0
}

# What deploy would say, without doing anything.
rack::deploy::status() {
    local name source target reload state
    while IFS=$'\t' read -r name source target reload; do
        state=$(rig::link::check "$source" "$target") || true
        printf '  %-12s %-9s %s\n' "$name" "$state" "${target/#$HOME/\~}"
    done < <(rack::manifest::select "$@")
}

# The one you need the moment you drop an app from the manifest.
rack::deploy::remove() {
    local name source target reload dotfiles removed=0
    dotfiles=$(rack::manifest::dotfiles)

    while IFS=$'\t' read -r name source target reload; do
        if ! rig::link::points_into "$target" "$dotfiles"; then
            [[ -e $target ]] && printf '  %-12s left alone (not ours)\n' "$name"
            continue
        fi
        if [[ ${RIG_DRY_RUN:-0} != 0 ]]; then
            printf '  %-12s would unlink\n' "$name"
            continue
        fi
        rig::link::remove "$target" --into "$dotfiles" &&
            printf '  %-12s unlinked\n' "$name"
        removed=$((removed + 1))
    done < <(rack::manifest::select "$@")

    ((removed)) || rig::log::info "nothing to remove"
}

# adopt <name...> — explicit form of the same move deploy --adopt makes.
rack::deploy::adopt() {
    (($#)) || {
        rig::log::error "adopt: name which entries to adopt"
        return "$RIG_EX_USAGE"
    }
    rack::deploy::run --adopt "$@"
}

rack::deploy::__default() { rack::deploy::run "$@"; }

rack::deploy::__usage() {
    cat <<'EOF'
  rack deploy                    everything in the manifest
  rack deploy hypr nvim          just these
  rack deploy --adopt            move what is already there into the repo first
  rack deploy --force            replace real files, moving them to
                                 ~/.local/state/rack/backups/<time>/
                                 (an app's untouched first-launch config
                                 is moved there without --force)
  rack deploy status             what it would do
  rack deploy remove nvim        unlink, but only links pointing into the repo

Idempotent: already-correct entries are left alone, so running this after a
git pull is the whole setup step. Honours RIG_DRY_RUN=1.
EOF
}
